### ISSUE TITLE
Keyboard events processed out of order

### ISSUE THREAD

**Issue by paulz** [inamiy/Harvest-SwiftUI-Gallery#15]
When I tried to type: Test into Todo list, I am getting "Tste"

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-26 at 14 11 00](https://user-images.githubusercontent.com/59230/73142622-c299c580-4045-11ea-88a9-59329d0a77da.png)

**Comment by inamiy** [comment]
This bug is also unreproducible at the moment (TBH I have never seen this before).

I will keep this issue opened.

**Comment by inamiy** [comment]
Reproduced the same issue reported in https://github.com/inamiy/Harvest-SwiftUI-Gallery/issues/14#issuecomment-619478666

**Comment by inamiy** [comment]
#20 (turning off TimeTravel debugging feature) will hopefully fix many UI glitches reported in #14, #15, #16 .

Please let me know if the same issues still occur.
